### ISSUE TITLE
 -gt: unary operator expected - OSX 10.11

### ISSUE THREAD

**Issue by Tastre** [sleemanj/gerb2etch#1]
Hi, I'm getting this error when running the script.

> gerb2etch -u copper
## Settings

Resolution: 600 (dpi)
Padding: 1 (mm)
Border: 0.25 (mm)
Separation: 30.4 (mm)
Rotate: Off
Negative Output: copper
Artwork To Create: copper top bottom
Mask all through holes minimum: 1.3 mm
## Show drill holes in mask: Off

Creating Artworks
Creating PDF
(standard_in) 90: parse error
/sw/bin/gerb2etch: line 695: [: -gt: unary operator expected
(standard_in) 91: parse error
/sw/bin/gerb2etch: line 715: [: -gt: unary operator expected
Tiling 2 x 3 per page.
Creating page 1...
mv: rename out/page-1.pdf to artwork.pdf: No such file or directory
Done

Any ideas?

`Darwin 192-168-1-1.tpgi.com.au 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`

**Comment by sleemanj** [comment]
Looks like the script did not find your gerbers and therefore did not create any artworks.

What gerber files are you using?

**Comment by Tastre** [comment]
Ok, thanks. My gerbers are .pho so I may need to convert them to .gbr.

**Comment by sleemanj** [comment]
Accepted file names for the layers are as follows...

| Layer | Name Your Files |
| --- | --- |
| Copper Top | *.gtl ; or Top.gbr |
| Silk Top | *.gto ; or TopSilk.gbr |
| Mask Top | *.gts ; or TopMask.gbr |
| Copper Bottom | *.gbl ; or Bottom.gbr |
| Silk Bottom | *.gbo ; or BottomSilk.gbr |
| Mask Bottom | *.gbs ; or BottomMask.gbr |
| Board Outline | *.gm1 ; or *.oln ; or Edges.gbr ; or BoardOutline.gbr |
| Drill | *.drl ; or drill.txt ; or Holes.gbr |
