### ISSUE TITLE
PDF not created

### ISSUE THREAD

**Issue by lekrom** [sleemanj/gerb2etch#3]
Hi @sleemanj 

Firstly, great work on this, truly epic...
Secondly, Full disclosure, I am a bit of a linux noob, so I may be be asking silly questions...

I have a slight issue, My gerber plots come out great (.png files). 
No pdf gets created though althoug your scrips appears to try to do so..
Here is the output:
Creating PDF
Tiling 2 x 1 per page.
Creating page 1...
Creating page 2...
Creating page 3...
mv: cannot stat 'out/page-*.pdf': No such file or directory
Notice: Multiple PDF documents created, see page-X.pdf ...

Am I doing something wrong?
Regards,
Lekrom

**Comment by sleemanj** [comment]
Try installing pdfjoin, or pdfjam, or texlive-extra-utils 

(the output you posted indicates that "pdfjoin" is not in the command line path, that tool comes from one of the above software packages depending on your distribution, at least in Ubuntu/Debian systems).

**Comment by lekrom** [comment]
Thanks, I will try it.

**Comment by lekrom** [comment]
Hi @sleemanj 

I have installed texlive-extra-utils. I still get the same result but with different error message:
Converting Gerbers To PNG
Creating Artworks
out/copper_bottom.png.png
out/etch_mask_bottom.png.png
out/silk_top_mirror.png.png
Creating PDF
Tiling 2 x 1 per page.
Creating page 1...
Creating page 2...
Joining pages into artwork.pdf
  pdfjam ERROR: out/page-*.pdf not found
Done

**Comment by lekrom** [comment]
Seems like the induvidual page pdf do not get created, so nothing for pdfjoin to actually join. If I use a single gerber file, I get the error I first reported: mv: cannot stat 'out/page-*.pdf': No such file or directory.
Running Ubuntu bionic beaver btw.

**Comment by sleemanj** [comment]
On this line
https://github.com/sleemanj/gerb2etch/blob/master/gerb2etch#L774
remove the 2>/dev/null from the end, that silences errors which might help you.

**Comment by lekrom** [comment]
OK, I found the issue.
Seems to be a security / policy issue with imagemagick. See this link: https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert

followed the instructions and it works fine now. Thanks for the assistance....
