### ISSUE TITLE
script errors when processing drill files w/ comments

### ISSUE THREAD

**Issue by csurf** [sleemanj/gerb2etch#5]
kicad produces drill files with comment lines that begin with semi-colons (see attached drill file). 

[example.drl.txt](https://github.com/sleemanj/gerb2etch/files/6017085/example.drl.txt)

Any 'weird/unexpected' characters in the comments section will cause the script to spew errors. 

here's an example:
```
LINE: TF.CreationDate,2021-02-20T17:09:14-08:00

(standard_in) 100: syntax error
(standard_in) 100: illegal character: :
(standard_in) 100: syntax error
(standard_in) 100: illegal character: :
(standard_in) 100: illegal character: :
(standard_in) 100: syntax error
```

I'm guessing a possible solution would be to simply skip over / 'continue' on any lines that begin w/ a semi-colon?

**Comment by sleemanj** [comment]
Around [line 282](https://github.com/sleemanj/gerb2etch/blob/e39e0acb1ec45e67606c3b908fc3463c2cf08eae/gerb2etch#L282) after the creation of Holes.gbr you could put something like

    if [ -f Holes.gbr ]
    then
      cat Holes.gbr | grep -Pv "^\s*;" >StrippedHoles.gbr
      mv StrippedHoles.gbr Holes.gbr
    fi

**Comment by csurf** [comment]
that patch seems to have worked, thanks.
