### ISSUE TITLE
add option to flip boards 90 degrees in output

### ISSUE THREAD

**Issue by csurf** [sleemanj/gerb2etch#6]
I'm not sure if this is already do-able, but would it be possible to add an option to be able to rotate the boards 90 degrees in the output?

My reasoning: I'm printing to 8.5 x 11" transparency sheets, and would like to try & save as much material as possible. If I have a 'tall' pcb, it would help if I could 'force the image on its side' in the final output. By doing this, I'd be able to use less of the transparency sheet's surface area, using more of its width at the top than it's length, and save a larger portion of the sheet for future use (not sure if that makes sense).

**Comment by sleemanj** [comment]
Option -z is for rotate
